### ISSUE TITLE
IndexError: pop index out of range with keras==1.2.2

### ISSUE THREAD

**Issue by SeekPoint** [sronnqvist/discourse-ablstm#3]
mldl@ub1604:~/ub16_prj/discourse-ablstm$ python3 train.py
Using TensorFlow backend.
Reading conll16st-zh-04-27-2016-blind-test/
Parses...
Relations...
5944 read

Reading conll16st-zh-04-27-2016-blind-test/
Parses...
Relations...
5944 read

Reading conll16st-zh-04-27-2016-blind-test/
Parses...
Relations...
1486 read

Maximum sequence length 256
Vocabulary: 5352
Classes: 10
Reading word vectors...
Mapping word vectors...
Validation size 5944
2018-09-14 15:05:57.956743: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-14 15:05:58.056369: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-14 15:05:58.056754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.61GiB
2018-09-14 15:05:58.056781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    attention1 = F.FarATTN(name="M_ATTN1")(lstm1)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/mldl/ub16_prj/discourse-ablstm/FarrokhAttentionLayer.py", line 33, in call
    alpha = K.softmax (K.dot(M, self.W) )
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 819, in dot
    y_permute_dim = [y_permute_dim.pop(-2)] + y_permute_dim
IndexError: pop index out of range
mldl@ub1604:~/ub16_prj/discourse-ablstm$

**Comment by sronnqvist** [comment]
Hi! The attention layer supports only Theano at the moment, please try to switch the backend.
